### ISSUE TITLE
got an error when syncing block from scratch

### ISSUE THREAD

**Issue by barryz** [oasysgames/oasys-validator#33]
#### System information

Geth version: `v1.0.6`
OS & Version: Windows/Linux/OSX
Commit hash : (if `v1.0.6`)

#### Expected behaviour

No error logs printed

#### Actual behaviour

Many error logs printed show as below:

```
ERROR[06-06|06:30:15.298] Failed to get validators                 in=Snapshot.apply hash=f4a1ce..a16ea7 number=1,013,760 err="header for hash not found"
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by tak1827** [comment]
syncing issue is resolved now #48
